# Generated by Django 3.2.6 on 2022-01-26 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_fooditem_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 22, 14, 1, 208639, tzinfo=utc), null=True),
        ),
    ]
