# Generated by Django 3.2.6 on 2022-01-26 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_fooditem_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
