# Generated by Django 3.2.6 on 2022-01-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_fooditem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_group',
            field=models.TextField(choices=[('fruits', 'fruits/vegetables'), ('fats', 'fats + oils'), ('dairy', 'eggs, milk and milk products'), ('meat', 'meat + fish'), ('herbs', 'herbs + spices'), ('grain', 'grain, nuts and baking products'), ('pasta', 'pasta, rice and pulses'), ('other', 'other')], default='other'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
