# Generated by Django 3.2.6 on 2022-01-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220126_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_group',
            field=models.TextField(choices=[('fruits', 'fruits (e.g. apples, bananas)'), ('vegetables', 'vegetables (e.g. broccoli, carrots)'), ('grains', 'grains(e.g. bread, rice, pasta)'), ('protein', 'protein (e.g. seafood, meat, eggs, nuts)'), ('dairy', 'dairy (e.g. milk, cheese, non-dairy alternatives)'), ('cooking product', 'cooking products (e.g. flour, cooking oil)'), ('herbs/spices', 'herbs + spices (e.g. sugar, salt, paprika)'), ('other', 'other')], default='other'),
        ),
    ]
