# Generated by Django 3.2.3 on 2022-01-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_fooditem_food_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='ing_lst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipelist',
            name='prep_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
