# Generated by Django 3.2.3 on 2022-02-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_recipelist_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipelist',
            name='ing_lst',
        ),
    ]
