# Generated by Django 3.2.3 on 2022-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_recipelist_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='prep_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
