# Generated by Django 3.2.6 on 2022-01-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 1, 26), null=True),
        ),
    ]
