# Generated by Django 3.2.3 on 2022-02-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220129_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
