# Generated by Django 3.2.3 on 2022-02-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_recipelist_ing_lst'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
