# Generated by Django 3.2.6 on 2022-02-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_recipegenerator_prep_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipegenerator',
            old_name='recipe_name',
            new_name='name',
        ),
    ]
